# Fee Config - melonbrew.org
# serveraccount - An account for fees to go too. (Blank for none)
# closespeed - How many milliseconds (1000 milliseconds is 1 second) before doors, trapdoors and gates auto close.
# globalcommands - A command followed by it's cost. For all players.
# groupcommands - Per group commands.

serveraccount:

closespeed: 5000

globalcommands:

groupcommands: