name: Fee

main: org.melonbrew.fee.Fee

version: 0.1

commands:
  fee:
    usage: Gives help
    description:
  "yes":
    usage: Accept this command
    description:

softdepend:
- Vault