name: Fee

main: org.melonbrew.fee.Fee

version: 0.1

commands:
  fee:
    usage: Gives help
    description:
  "yes":
    usage: Accept this command
    description:

permissions:
  fee.sign:
    usage: Allows you to make a Fee sign
  fee.sign.other:
    usage: Allows you to make a sign with another player's name
  fee.?:
    usage: Allows you to check the help
  fee.exempt:
    usage: Exempts a player from all fees
  fee.reload:
    usage: Allows you to reload the config
  fee.member:
    children:
      fee.sign: true
      fee.?: true
    default: true
  fee.admin:
    children:
      fee.reload: true
      fee.sign.other: true

softdepend:
- Vault