name: Fee

main: org.melonbrew.fee.Fee

version: 0.1

commands:
  fee:
    usage: Gives help
    description:
  "yes":
    usage: Accept this command
    description:

permissions:
  fee.exempt:
    usage: Exempts a player from all fees
  fee.?:
    usage: Allows you to check the help
  fee.reload:
    usage: Allows you to reload the config

softdepend:
- Vault